'use strict';
const DB='patrimoine-simple-db',VER=1;let db,deferredPrompt;let state={view:'dashboard',positions:[],assetTransactions:[],contributions:[],settings:{usdToEur:.8474576271}};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const eur=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}),num=new Intl.NumberFormat('fr-FR',{maximumFractionDigits:8}),dateFmt=new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium'});const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=(v,c)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:c,maximumFractionDigits:2}).format(v);const pct=v=>`${v>=0?'+':''}${v.toFixed(2).replace('.',',')} %`;const today=()=>new Date().toISOString().slice(0,10);
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{for(const [n,k] of [['positions','id'],['assetTransactions','id'],['contributions','id'],['settings','key']])if(!r.result.objectStoreNames.contains(n))r.result.createObjectStore(n,{keyPath:k})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}function req(s,m,a){return new Promise((res,rej)=>{const r=a(db.transaction(s,m).objectStore(s));r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}const all=s=>req(s,'readonly',o=>o.getAll()),put=(s,v)=>req(s,'readwrite',o=>o.put(v)),del=(s,k)=>req(s,'readwrite',o=>o.delete(k)),clear=s=>req(s,'readwrite',o=>o.clear());
async function seed(force=false){const existing=await all('positions');if(existing.length&&!force)return;for(const s of ['positions','assetTransactions','contributions','settings'])await clear(s);const d=await fetch('./assets/seed.json').then(r=>r.json());for(const x of d.positions)await put('positions',x);for(const x of d.assetTransactions)await put('assetTransactions',x);for(const x of d.contributions)await put('contributions',x);for(const [key,value] of Object.entries(d.settings))await put('settings',{key,value})}async function load(){state.positions=await all('positions');state.assetTransactions=await all('assetTransactions');state.contributions=await all('contributions');state.settings=Object.fromEntries((await all('settings')).map(x=>[x.key,x.value]));render()}
function livePositions(){return state.positions.map(p=>{let quantity=+p.quantity,cost=Number.isFinite(+p.costBasis)?+p.costBasis:quantity*(+p.averageCost);const tx=state.assetTransactions.filter(t=>t.positionId===p.id).sort((a,b)=>a.date.localeCompare(b.date));for(const t of tx){const q=+t.quantity,price=+t.unitPrice,fees=+t.fees||0;if(t.type==='BUY'){quantity+=q;cost+=q*price+fees}else if(t.type==='SELL'){const avg=quantity?cost/quantity:0;quantity-=q;cost=Math.max(0,cost-avg*q)}else if(t.type==='REWARD'){quantity+=q}else if(t.type==='ADJUSTMENT'){quantity+=q}}const avg=quantity?cost/quantity:0,value=quantity*(+p.currentPrice),gain=value-cost,perf=cost?gain/cost*100:0;return {...p,quantity,cost,averageCost:avg,value,gain,perf}})}const toEUR=(v,c)=>c==='USD'?v*(+state.settings.usdToEur||0):v;
function totals(){const ps=livePositions();return {ps,value:ps.reduce((s,p)=>s+toEUR(p.value,p.currency),0),cost:ps.reduce((s,p)=>s+toEUR(p.cost,p.currency),0)}}
function portfolioBreakdown(){const ps=livePositions(),crypto=ps.filter(p=>p.category==='Crypto'),other=ps.filter(p=>p.category!=='Crypto');return {ps,crypto,other,cryptoValue:crypto.reduce((s,p)=>s+p.value,0),cryptoCost:crypto.reduce((s,p)=>s+p.cost,0),otherValue:other.reduce((s,p)=>s+toEUR(p.value,p.currency),0),otherCost:other.reduce((s,p)=>s+toEUR(p.cost,p.currency),0)}}
function contributionTotals(){const crypto=state.contributions.filter(c=>c.domain==='Crypto').reduce((s,c)=>s+(+c.amount),0),bourse=state.contributions.filter(c=>c.domain==='Bourse').reduce((s,c)=>s+(+c.amount),0);return {crypto,bourse,total:crypto+bourse}}
function destinationTotals(){const m={};for(const c of state.contributions){const k=c.destination||'Non précisé';m[k]=(m[k]||0)+(+c.amount)}return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function annual(){const m={};for(const c of state.contributions){const y=c.date.slice(0,4);m[y]??={Crypto:0,Bourse:0};m[y][c.domain]= (m[y][c.domain]||0)+(+c.amount)}return Object.entries(m).sort((a,b)=>b[0].localeCompare(a[0]))}
function assetCards(ps){return `<div class="settings-grid">${ps.map(p=>`<article class="card position-card" data-position="${p.id}"><div class="asset-id"><div class="symbol">${esc(p.symbol.slice(0,4))}</div><div><b>${esc(p.name)}</b><span class="muted">${esc(p.account)}</span></div></div><div class="detail-grid"><div><span class="label">Valeur</span><b>${money(p.value,p.currency)}</b></div><div><span class="label">Quantité</span><b>${num.format(p.quantity)}</b></div><div><span class="label">PRU</span><b>${money(p.averageCost,p.currency)}</b></div><div><span class="label">Performance</span><b class="${p.gain>=0?'good':'bad'}">${pct(p.perf)}</b></div></div></article>`).join('')}</div>`}
function dashboard(){
  const {cryptoValue,otherValue}=portfolioBreakdown();
  const invested=contributionTotals();
  const rate=+state.settings.usdToEur||0;
  const cryptoValueEUR=cryptoValue*rate;
  const currentTotalEUR=cryptoValueEUR+otherValue;
  const cryptoGainEUR=cryptoValueEUR-invested.crypto;
  const bourseGainEUR=otherValue-invested.bourse;
  const globalGainEUR=currentTotalEUR-invested.total;
  const cryptoPerf=invested.crypto?cryptoGainEUR/invested.crypto*100:0;
  const boursePerf=invested.bourse?bourseGainEUR/invested.bourse*100:0;
  const globalPerf=invested.total?globalGainEUR/invested.total*100:0;
  return `<section class="card home-summary">
    <span class="label">Apports cumulés depuis le début</span>
    <div class="value">${eur.format(invested.total)}</div>
    <div class="summary-split">
      <div><span>Crypto</span><b>${eur.format(invested.crypto)}</b></div>
      <div><span>Bourse</span><b>${eur.format(invested.bourse)}</b></div>
    </div>
  </section>
  <section class="card performance-main">
    <span class="label">Performance globale à l’instant T</span>
    <div class="value ${globalGainEUR>=0?'good':'bad'}">${globalGainEUR>=0?'+':''}${eur.format(globalGainEUR)}</div>
    <div class="performance-percent ${globalGainEUR>=0?'good':'bad'}">${pct(globalPerf)}</div>
    <div class="valuation-line"><span>Valeur actuelle Crypto + Bourse</span><b>${eur.format(currentTotalEUR)}</b></div>
    <p class="muted">La valeur des cryptos est convertie en euros avec le taux enregistré : 1 $ = ${rate.toFixed(4).replace('.',',')} €.</p>
  </section>
  <section class="performance-grid">
    <article class="card">
      <div class="section-label">CRYPTO</div>
      <div class="metric-row"><span>Valeur actuelle</span><b>${money(cryptoValue,'USD')}</b></div>
      <div class="metric-row"><span>Équivalent en euros</span><b>${eur.format(cryptoValueEUR)}</b></div>
      <div class="metric-row"><span>Apports cumulés</span><b>${eur.format(invested.crypto)}</b></div>
      <div class="category-result ${cryptoGainEUR>=0?'good':'bad'}">${cryptoGainEUR>=0?'+':''}${eur.format(cryptoGainEUR)} · ${pct(cryptoPerf)}</div>
    </article>
    <article class="card">
      <div class="section-label">BOURSE</div>
      <div class="metric-row"><span>Valeur actuelle</span><b>${eur.format(otherValue)}</b></div>
      <div class="metric-row"><span>Apports cumulés</span><b>${eur.format(invested.bourse)}</b></div>
      <div class="category-result ${bourseGainEUR>=0?'good':'bad'}">${bourseGainEUR>=0?'+':''}${eur.format(bourseGainEUR)} · ${pct(boursePerf)}</div>
    </article>
  </section>
  <div class="section-head"><h2>Apports par année</h2><button class="secondary" data-go="contributions">Voir le détail</button></div>
  ${annualTable(annual().slice(0,8))}`
}
function annualTable(rows=annual()){return `<article class="card"><table class="annual-table"><thead><tr><th>Année</th><th>Crypto</th><th>Bourse</th><th>Total</th></tr></thead><tbody>${rows.map(([y,v])=>`<tr><td><b>${y}</b></td><td>${eur.format(v.Crypto||0)}</td><td>${eur.format(v.Bourse||0)}</td><td><b>${eur.format((v.Crypto||0)+(v.Bourse||0))}</b></td></tr>`).join('')}</tbody></table></article>`}
function portfolio(){
  const ps=livePositions();
  const crypto=ps.filter(p=>p.category==='Crypto');
  const bourse=ps.filter(p=>p.category!=='Crypto');
  return `<div class="section-head"><div><h2>Portefeuille</h2><span class="muted">Positions actuelles, mises à jour par vos nouvelles opérations</span></div><button class="primary" id="newAssetTx">Nouvelle opération</button></div>
  <div class="category-title"><span>Crypto</span><small>Valeurs en dollars</small></div>
  ${assetCards(crypto)}
  <div class="category-title"><span>Bourse</span><small>Valeurs en euros</small></div>
  ${assetCards(bourse)}
  <div class="section-head"><h2>Cours actuels saisis manuellement</h2></div>
  <div class="settings-grid">${ps.map(p=>`<article class="card"><b>${esc(p.symbol)} · ${esc(p.name)}</b><form class="price-form" data-id="${p.id}" style="display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:12px"><input name="price" type="number" step="any" value="${p.currentPrice}"><button class="secondary">Mettre à jour (${p.currency})</button></form></article>`).join('')}</div>`
}
function operations(){const tx=[...state.assetTransactions].sort((a,b)=>b.date.localeCompare(a.date));return `<div class="section-head"><div><h2>Opérations depuis le point de départ</h2><span class="muted">Les anciennes transactions détaillées ne sont pas reprises.</span></div><button class="primary" id="newAssetTx">Ajouter</button></div><div class="compact-list">${tx.map(t=>{const p=state.positions.find(x=>x.id===t.positionId)||{};return `<article class="compact-row"><div><b>${dateFmt.format(new Date(t.date+'T12:00:00'))}</b></div><div><b>${esc(p.symbol)} · ${esc({BUY:'Achat',SELL:'Vente',REWARD:'Récompense',ADJUSTMENT:'Correction'}[t.type])}</b><span class="muted">${num.format(t.quantity)} à ${money(t.unitPrice,p.currency||'EUR')}</span></div><div class="hide-mobile">${esc(t.note||'')}</div><button class="danger" data-delete-tx="${t.id}">×</button></article>`}).join('')||'<div class="empty card">Aucune nouvelle opération. Votre portefeuille repose pour le moment uniquement sur la position initiale.</div>'}</div>`}
function contributions(){const rows=[...state.contributions].sort((a,b)=>b.date.localeCompare(a.date)),{crypto,bourse,total}=contributionTotals(),destinations=destinationTotals();return `<section class="kpi-grid"><article class="card kpi"><span class="label">TOTAL INVEST — Crypto</span><strong>${eur.format(crypto)}</strong></article><article class="card kpi"><span class="label">TOTAL INVEST — Bourse</span><strong>${eur.format(bourse)}</strong></article><article class="card kpi"><span class="label">TOTAL INVEST global</span><strong>${eur.format(total)}</strong></article></section><div class="section-head"><div><h2>Suivi global des sommes investies</h2><span class="muted">Reprise du tableau TOTAL INVEST. Tous les montants de cette section sont en euros.</span></div><button class="primary" id="newContribution">Ajouter un investissement</button></div>${annualTable()}<div class="section-head"><h2>Répartition par destination</h2></div><article class="card"><table class="annual-table"><thead><tr><th>Compte / plateforme</th><th>Total net investi</th></tr></thead><tbody>${destinations.map(([name,amount])=>`<tr><td><b>${esc(name)}</b></td><td><b>${eur.format(amount)}</b></td></tr>`).join('')}</tbody></table></article><div class="section-head"><h2>Détail TOTAL INVEST</h2></div><div class="compact-list">${rows.map(c=>`<article class="compact-row"><div><b>${dateFmt.format(new Date(c.date+'T12:00:00'))}</b></div><div><b>${esc(c.domain)} · ${esc(c.destination)}</b><span class="muted">${esc(c.note||'')}</span></div><div class="hide-mobile"><b class="${c.amount>=0?'good':'bad'}">${eur.format(c.amount)}</b></div><div class="button-row"><button class="secondary" data-edit-contribution="${c.id}">✎</button><button class="danger" data-delete-contribution="${c.id}">×</button></div></article>`).join('')}</div>`}

function settings(){return `<div class="settings-grid"><article class="card"><h3>Conversion USD → EUR</h3><p class="muted">Taux manuel utilisé uniquement pour consolider le tableau de bord.</p><form id="rateForm"><label>Valeur de 1 USD en EUR<input name="rate" type="number" step="any" value="${state.settings.usdToEur}"></label><button class="primary" style="margin-top:12px">Enregistrer</button></form></article><article class="card"><h3>Sauvegarde</h3><p class="muted">Vos données restent sur cet appareil. Exportez-les régulièrement.</p><div class="button-row"><button class="secondary" id="exportBtn">Exporter JSON</button><label class="file-label">Restaurer JSON<input id="importInput" type="file" accept="application/json" hidden></label></div></article><article class="card"><h3>Réinitialisation</h3><p class="muted">Restaure la photographie initiale et l’historique des apports Crypto/Bourse. Toutes les nouvelles opérations seront supprimées.</p><button class="danger" id="resetBtn">Restaurer les données initiales</button></article><article class="card"><h3>Principe de calcul</h3><div class="notice">Un apport de 500 € vers Binance augmente les apports Crypto, mais ne modifie aucune quantité. Un achat de BTC modifie la quantité et recalcule le PRU.</div></article></div>`}
function render(){const a=$('#app');a.innerHTML=state.view==='dashboard'?dashboard():state.view==='portfolio'?portfolio():state.view==='operations'?operations():state.view==='contributions'?contributions():settings();$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));bind()}
function openAsset(){const f=$('#assetForm');f.reset();f.date.value=today();f.positionId.innerHTML=state.positions.map(p=>`<option value="${p.id}">${esc(p.symbol)} · ${esc(p.name)}</option>`).join('');$('#assetDialog').showModal()}function openContribution(c={}){const f=$('#contributionForm');f.reset();f.date.value=c.date||today();for(const [k,v] of Object.entries(c))if(f.elements[k])f.elements[k].value=v;$('#contributionTitle').textContent=c.id?'Modifier l’apport':'Ajouter un apport';$('#contributionDialog').showModal()}
function bind(){$$('[data-go]').forEach(b=>b.onclick=()=>{state.view=b.dataset.go;render()});const n=$('#newAssetTx');if(n)n.onclick=openAsset;const nc=$('#newContribution');if(nc)nc.onclick=()=>openContribution();$$('.price-form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const p=state.positions.find(x=>x.id===f.dataset.id);p.currentPrice=+f.price.value;await put('positions',p);await load()});$$('[data-delete-tx]').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer cette opération ?')){await del('assetTransactions',b.dataset.deleteTx);await load()}});$$('[data-edit-contribution]').forEach(b=>b.onclick=()=>openContribution(state.contributions.find(c=>c.id===b.dataset.editContribution)));$$('[data-delete-contribution]').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer cet apport ?')){await del('contributions',b.dataset.deleteContribution);await load()}});const rf=$('#rateForm');if(rf)rf.onsubmit=async e=>{e.preventDefault();await put('settings',{key:'usdToEur',value:+rf.rate.value});await load()};if($('#exportBtn'))$('#exportBtn').onclick=exportData;if($('#importInput'))$('#importInput').onchange=importData;if($('#resetBtn'))$('#resetBtn').onclick=async()=>{if(confirm('Restaurer les données initiales ?')){await seed(true);await load()}}}
$('#assetForm').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.currentTarget));x.id=crypto.randomUUID();x.quantity=+x.quantity;x.unitPrice=+x.unitPrice;x.fees=+x.fees||0;await put('assetTransactions',x);$('#assetDialog').close();await load()};$('#contributionForm').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.currentTarget));x.id=x.id||crypto.randomUUID();x.amount=+x.amount;await put('contributions',x);$('#contributionDialog').close();await load()};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$$('.bottom-nav button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();scrollTo({top:0,behavior:'smooth'})});
async function exportData(){const d={version:3,exportedAt:new Date().toISOString(),positions:await all('positions'),assetTransactions:await all('assetTransactions'),contributions:await all('contributions'),settings:Object.fromEntries((await all('settings')).map(x=>[x.key,x.value]))};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download=`patrimoine-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}async function importData(e){try{const d=JSON.parse(await e.target.files[0].text());for(const s of ['positions','assetTransactions','contributions','settings'])await clear(s);for(const x of d.positions||[])await put('positions',x);for(const x of d.assetTransactions||[])await put('assetTransactions',x);for(const x of d.contributions||[])await put('contributions',x);for(const [key,value] of Object.entries(d.settings||{}))await put('settings',{key,value});await load()}catch(err){alert('Fichier invalide : '+err.message)}finally{e.target.value=''}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};(async()=>{try{db=await openDB();await seed();await load();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')}catch(e){$('#app').innerHTML=`<div class="card bad">Erreur : ${esc(e.message)}</div>`}})();