import React,{useEffect,useMemo,useState} from 'react';
import {SafeAreaView,View,Text,StyleSheet,FlatList,Pressable,TextInput,Modal,ScrollView,Alert} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {addTransaction,getPrices,getTransactions,initDb,resetDb,updatePrice,Tx} from '../src/db/database';
const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n||0);
export default function App(){const [tab,setTab]=useState('Tableau');const [tx,setTx]=useState<Tx[]>([]);const [prices,setPrices]=useState<any[]>([]);const [modal,setModal]=useState(false);const [symbol,setSymbol]=useState('BTC');const [amount,setAmount]=useState('');
 const load=()=>{setTx(getTransactions());setPrices(getPrices())};useEffect(()=>{initDb();load()},[]);
 const usd=.8474576271; const holdings=useMemo(()=>{const m:any={};for(const t of tx){const s=t.assetSymbol;m[s]??={symbol:s,name:t.assetName,category:t.category,qty:0,invested:0,currency:t.currency};const sign=t.type==='SELL'?-1:1;m[s].qty+=sign*t.quantity;m[s].invested+=sign*t.totalAmount+(t.fees||0)}return Object.values(m).map((h:any)=>{const p=prices.find(x=>x.symbol===h.symbol);const rate=(p?.currency==='USD'?usd:1);const value=h.qty*(p?.price??h.invested/(h.qty||1))*rate;const invested=h.invested*(h.currency==='USD'?usd:1);return {...h,value,invested,gain:value-invested}})},[tx,prices]);
 const total=holdings.reduce((a:any,h:any)=>a+h.value,0), invested=holdings.reduce((a:any,h:any)=>a+h.invested,0);
 const add=()=>{const a=Number(amount);if(!a)return;const p=prices.find(x=>x.symbol===symbol);const h:any=holdings.find((x:any)=>x.symbol===symbol);const t:any={id:String(Date.now()),assetSymbol:symbol,assetName:h?.name||symbol,category:h?.category||'Autre',account:'Saisie manuelle',type:'BUY',date:new Date().toISOString().slice(0,10),quantity:a/(p?.price||1),unitPrice:p?.price||1,totalAmount:a,fees:0,currency:p?.currency||'EUR',note:'Ajout manuel'};addTransaction(t);setAmount('');setModal(false);load()};
 return <SafeAreaView style={s.safe}><StatusBar style="auto"/><View style={s.header}><Text style={s.title}>Mon Patrimoine</Text><Text style={s.sub}>100 % local · 286 opérations historiques</Text></View>
 <View style={s.tabs}>{['Tableau','Portefeuille','Historique','Cours'].map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.tab,tab===x&&s.active]}><Text>{x}</Text></Pressable>)}</View>
 {tab==='Tableau'&&<ScrollView contentContainerStyle={s.content}><View style={s.hero}><Text style={s.label}>Patrimoine estimé</Text><Text style={s.big}>{money(total)}</Text><Text style={s.gain}>{money(total-invested)} · {invested?((total-invested)/invested*100).toFixed(1):0}%</Text></View><Text style={s.h2}>Répartition</Text>{Object.entries(holdings.reduce((m:any,h:any)=>(m[h.category]=(m[h.category]||0)+h.value,m),{})).map(([k,v]:any)=><View style={s.row} key={k}><Text>{k}</Text><Text style={s.bold}>{money(v)}</Text></View>)}</ScrollView>}
 {tab==='Portefeuille'&&<FlatList contentContainerStyle={s.content} data={holdings} keyExtractor={(x:any)=>x.symbol} renderItem={({item}:any)=><View style={s.card}><View><Text style={s.bold}>{item.name}</Text><Text style={s.muted}>{item.symbol} · {item.category}</Text></View><View style={{alignItems:'flex-end'}}><Text style={s.bold}>{money(item.value)}</Text><Text style={{color:item.gain>=0?'green':'crimson'}}>{money(item.gain)}</Text></View></View>} />}
 {tab==='Historique'&&<FlatList contentContainerStyle={s.content} data={tx} keyExtractor={x=>x.id} renderItem={({item})=><View style={s.card}><View style={{flex:1}}><Text style={s.bold}>{item.assetSymbol} · {item.type}</Text><Text style={s.muted}>{item.date} · {item.account}</Text></View><Text>{item.totalAmount.toFixed(2)} {item.currency}</Text></View>} />}
 {tab==='Cours'&&<ScrollView contentContainerStyle={s.content}>{prices.map(p=><View style={s.card} key={p.symbol}><View><Text style={s.bold}>{p.symbol}</Text><Text style={s.muted}>Mis à jour {p.updatedAt}</Text></View><TextInput style={s.price} defaultValue={String(Number(p.price.toFixed(6)))} keyboardType="decimal-pad" onEndEditing={e=>{const v=Number(e.nativeEvent.text.replace(',','.'));if(v>0){updatePrice(p.symbol,v,p.currency);load()}}}/></View>)}<Pressable style={s.danger} onPress={()=>Alert.alert('Réinitialiser','Restaurer tout l’historique initial ?',[{text:'Annuler'},{text:'Oui',onPress:()=>{resetDb();load()}}])}><Text>Restaurer les données initiales</Text></Pressable></ScrollView>}
 <Pressable style={s.fab} onPress={()=>setModal(true)}><Text style={{fontSize:28}}>＋</Text></Pressable>
 <Modal visible={modal} animationType="slide" transparent><View style={s.overlay}><View style={s.sheet}><Text style={s.h2}>Ajouter un achat</Text><TextInput style={s.input} value={symbol} onChangeText={setSymbol} placeholder="Symbole"/><TextInput style={s.input} value={amount} onChangeText={setAmount} placeholder="Montant" keyboardType="decimal-pad"/><Pressable style={s.primary} onPress={add}><Text style={{color:'white',fontWeight:'700'}}>Enregistrer</Text></Pressable><Pressable onPress={()=>setModal(false)}><Text style={{textAlign:'center',marginTop:16}}>Annuler</Text></Pressable></View></View></Modal></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f6f8'},header:{padding:20,paddingBottom:10},title:{fontSize:28,fontWeight:'800'},sub:{color:'#667085'},tabs:{flexDirection:'row',paddingHorizontal:12,gap:4},tab:{flex:1,padding:10,alignItems:'center',borderRadius:10},active:{backgroundColor:'white'},content:{padding:16,paddingBottom:100},hero:{backgroundColor:'#111827',padding:24,borderRadius:20},label:{color:'#cbd5e1'},big:{color:'white',fontSize:34,fontWeight:'800',marginVertical:8},gain:{color:'#86efac'},h2:{fontSize:20,fontWeight:'800',marginVertical:16},row:{flexDirection:'row',justifyContent:'space-between',backgroundColor:'white',padding:16,borderRadius:12,marginBottom:8},bold:{fontWeight:'700'},muted:{color:'#667085',fontSize:12},card:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',backgroundColor:'white',padding:16,borderRadius:14,marginBottom:10},fab:{position:'absolute',right:20,bottom:24,width:58,height:58,borderRadius:29,backgroundColor:'#fbbf24',alignItems:'center',justifyContent:'center'},overlay:{flex:1,backgroundColor:'#0007',justifyContent:'flex-end'},sheet:{backgroundColor:'white',padding:24,borderTopLeftRadius:24,borderTopRightRadius:24},input:{borderWidth:1,borderColor:'#d0d5dd',borderRadius:12,padding:14,marginBottom:12},primary:{backgroundColor:'#111827',padding:16,borderRadius:12,alignItems:'center'},price:{borderWidth:1,borderColor:'#d0d5dd',padding:8,borderRadius:8,minWidth:120,textAlign:'right'},danger:{padding:16,alignItems:'center',borderWidth:1,borderColor:'#ef4444',borderRadius:12,marginTop:18}})
